#! /usr/bin/env bash
RED="\e[31m";
GREEN="\e[32m";
ENDCOLOR="\e[0m";
KO="KO";

if [ -z $1 ]; then
	echo "Enter the number of values to sort"
	exit
fi
if [ -z $2 ]; then
	echo "Enter the max number of actions"
	exit
else
	max_steps=$2;
fi
if ! [[ $1 =~ ^[0-9]+$ ]]; then
	echo "Error: first argument is not a number"
	exit
fi
if ! [[ $2 =~ ^[0-9]+$ ]]; then
	echo "Error: second argument is not a number"
	exit
fi
while [ 1 ]
do 
	rand=`ruby -e "puts (-1000..10000).to_a.shuffle.sample($1).join(' ')"`;
	num=$(./push_swap $rand | grep -E "^(sa|sb|pa|pb|ra|rb|rr|rra|rrb|rrr)" | wc -l);
	is_ok=$(./push_swap $rand | ./checker $rand);
	if [[ $is_ok == *"KO"* ]]
	then
		echo "$(tput setaf 1)ERROR: The Numbers |$rand| are unstored $(tput sgr0)";
		exit;
	elif [[ $is_ok == *"Error"* ]]
	then
		echo "$(tput setaf 1)ERROR happend while storing following numbers |$rand| $(tput sgr0)";
		exit;
	fi
	if [ $num -ge $max_steps ]
	then
		echo "$(tput setaf 1)ERROR: |$rand| sorted in '$num' instead of '$max_steps' $(tput sgr0)";
		exit;
	fi
	echo -e "$(tput setaf 2)$1 numbers sorted in : $num \r\t\t\t\t $is_ok$(tput sgr0)";
done
